@startuml
skinparam linetype ortho
skinparam monochrome false
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

entity "User" {
  * _id
  --
  fullName
  email
  phone
  role
  passwordHash
  avatarUrl
  lastLogin
  status
  createdAt
  updatedAt
}

entity "Venue" {
  * _id
  --
  + ownerId
  name
  address
  coordinates
  description
  openTime
  closeTime
  averageRating
  pricePerHour
  status
  statusReason
  createdAt
  updatedAt
}

entity "AIAnalysisMetadata" {
  * _id
  --
  + venueId
  peakHoursPrediction
  lastAnalyzedAt
}

entity "PlayerSearchHistory" {
  * _id
  --
  + playerId
  searchedAddress
  searchedCoordinates
  createdAt
}

entity "SlotLock" {
  * _id
  --
  + courtId
  date
  startTime
  endTime
  userId
  createdAt
  updatedAt
}

entity "BookingDetail" {
  * _id
  --
  + bookingId
  + courtId
  bookingDate
  startTime
  endTime
  price
  createdAt
}

entity "Booking" {
  * _id
  --
  + playerId
  isGuest
  + venueId
  + promotionId
  totalPrice
  finalPrice
  status
  note
  isWeekly
  customerName
  customerPhone
  customerEmail
  createdAt
  updatedAt
}

entity "CourtUnavailableTime" {
  * _id
  --
  + courtId
  startDatetime
  endDatetime
  reason
  createdAt
}

entity "Court" {
  * _id
  --
  + venueId
  name
  type
  status
  createdAt
}

entity "Notification" {
  * _id
  --
  + user_id
  title
  body
  type
  is_read
  createdAt
}

entity "OwnerRequest" {
  * _id
  --
  + userId
  identityCard
  courtAddress
  courtImages
  businessLicense
  status
  rejectReason
  createdAt
  updatedAt
}

entity "Payment" {
  * _id
  --
  + bookingId
  amount
  method
  status
  transaction_id
  createdAt
}

entity "Pricing" {
  * _id
  --
  + venueId
  dayOfWeek
  startTime
  endTime
  pricePerHour
  createdAt
}

entity "Promotion" {
  * _id
  --
  + venueId
  code
  discountPercentage
  maxDiscountAmount
  startDate
  endDate
  isActive
  createdAt
}

entity "Review" {
  * _id
  --
  + venueId
  + playerId
  rating
  comment
  + likes
  createdAt
}

entity "VenueImage" {
  * _id
  --
  + venueId
  imageUrl
  isPrimary
  createdAt
}

Venue "*" --> "1" User : ownerId
AIAnalysisMetadata "*" --> "1" Venue : venueId
PlayerSearchHistory "*" --> "1" User : playerId
SlotLock "*" --> "1" Court : courtId
BookingDetail "*" --> "1" Booking : bookingId
BookingDetail "*" --> "1" Court : courtId
Booking "*" --> "1" User : playerId
Booking "*" --> "1" Venue : venueId
Booking "*" --> "1" Promotion : promotionId
CourtUnavailableTime "*" --> "1" Court : courtId
Court "*" --> "1" Venue : venueId
Notification "*" --> "1" User : user_id
OwnerRequest "*" --> "1" User : userId
Payment "*" --> "1" Booking : bookingId
Pricing "*" --> "1" Venue : venueId
Promotion "*" --> "1" Venue : venueId
Review "*" --> "1" Venue : venueId
Review "*" --> "1" User : playerId
Review "*" --> "*" User : likes
VenueImage "*" --> "1" Venue : venueId
@enduml
